services:
  prometheus:
    image: prom/prometheus
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - /mnt/gfs/docker/monitoring/prometheus-config:/etc/prometheus
      - /mnt/gfs/docker/monitoring/prometheus-data:/prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    command: -docker_only
    labels:
      prometheus-job: cadvisor
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 8085
        mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  alertmanager:
    image: quay.io/prometheus/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /mnt/gfs/docker/monitoring/alertmanager:/etc/alertmanager

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /mnt/gfs/docker/monitoring/grafana:/var/lib/grafana
    restart: unless-stopped
